import os
from pathlib import Path
from dotenv import load_dotenv

# Search for .env in current directory, backend directory, or parent directory
env_paths = [
    Path.cwd() / ".env",
    Path(__file__).parent / ".env",
    Path(__file__).parent.parent / ".env",
]

for p in env_paths:
    if p.exists():
        load_dotenv(p)
        break

BASE_URL = os.getenv("BASE_URL", "http://192.168.20.152:2408/v1").rstrip("/")
API_KEY = os.getenv("API_KEY", "EMPTY")
DEFAULT_MODEL = os.getenv("DEFAULT_MODEL", "qwen35_4b")
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "8000"))
APP_TITLE = os.getenv("APP_TITLE", "ChatGPT (vLLM + LangGraph)")

# Token limits per session configurable via .env
# MAX_SESSION_TOKENS: Total maximum context tokens per session/request
# MAX_RESPONSE_TOKENS: Maximum completion tokens generated by the model
MAX_SESSION_TOKENS = int(os.getenv("MAX_SESSION_TOKENS", "2048"))
MAX_RESPONSE_TOKENS = int(os.getenv("MAX_RESPONSE_TOKENS", "2048"))

# SQLite Database & Authentication Configuration
default_db = Path(__file__).resolve().parent / "data" / "chatbot.db"
SQLITE_DB_PATH = Path(os.getenv("SQLITE_DB_PATH", str(default_db))).resolve()
SESSION_EXPIRE_HOURS = int(os.getenv("SESSION_EXPIRE_HOURS", "72"))
